### ISSUE TITLE
broot theme doesnt work

### ISSUE THREAD

**Issue by dchinmay2** [srcery-colors/srcery-shell#2]
the broot theme, when saved to `~/.config/broot/conf.toml` doesnt change colours

note - everything in the skin section seems commented out

**Comment by MindTooth** [comment]
@barskern Thoughts?

**Comment by dchinmay2** [comment]
i uncommented the section, it doesn't look like it has changed much

**Comment by dchinmay2** [comment]
i mean, it is not as "vibrant" as srcery

**Comment by barskern** [comment]
You have to copy the contents of the `broot/conf.toml` in this repository at the end of your `~/.config/broot/conf.toml`. My full config file looks like this:

```toml

# This configuration file lets you define new commands
# or change the shortcut or triggering keys of built-in verbs.
# You can change the colors of broot too.
#
# Configuration documentation is available at https://dystroy.org/broot
#

#####################
# user defined verbs:

# If $EDITOR isn't set on your computer, you should either set it
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
[[verbs]]
invocation = "edit"
key = "ctrl-o"
shortcut = "e"
execution = "$EDITOR {file}"
leave_broot = false

[[verbs]]
key = "ctrl-n"
execution = ":line_down"

[[verbs]]
key = "ctrl-p"
execution = ":line_up"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

#####################
# Skin

# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values
# Note that some of those colors might not correcly
# render on terminals with low capabilities
#
[skin]
default = "rgb(252, 232, 195) rgb(28, 27, 25)"
tree = "rgb(182, 168, 141) none"
file = "rgb(252, 232, 195) none"
directory = "rgb(104, 168, 228) none bold"
exe = "rgb(152, 188, 55) none"
link = "rgb(255, 92, 143) none"
pruning = "rgb(89, 73, 101) none Italic"
permissions = "rgb(182, 168, 141) none"
owner = "rgb(182, 168, 141) none"
group = "rgb(182, 168, 141) none"
selected_line = "none rgb(48, 48, 48)"
char_match = "rgb(251, 184, 41) none"
file_error = "rgb(247, 83, 65) none"
flag_label = "rgb(182, 168, 141) none"
flag_value = "rgb(251, 184, 41) none bold"
input = "rgb(252, 232, 195) none"
status_error = "rgb(247, 83, 65) rgb(38, 38, 38)"
status_job = "rgb(252, 232, 195) rgb(58, 58, 58)"
status_normal = "gray(20) rgb(38, 38, 38)"
status_italic = "rgb(251, 184, 41) rgb(38, 38, 38)"
status_bold = "rgb(251, 184, 41) none bold"
status_code = "rgb(81, 159, 80) rgb(38, 38, 38)"
status_ellipsis = "rgb(182, 168, 141) rgb(38, 38, 38)"
scrollbar_track = "rgb(38, 38, 38) none"
scrollbar_thumb = "rgb(251, 184, 41) none"
help_paragraph = "rgb(252, 232, 195) none"
help_bold = "rgb(252, 232, 195) none bold"
help_italic = "rgb(255, 92, 143) none italic"
help_code = "rgb(255, 92, 143) none"
help_headers = "rgb(251, 184, 41) none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds
```

@p00f What does your config file looks like?
